'use client';

import React, { useState } from 'react';
import { useTranslations, useLocale } from 'next-intl';
import { Link } from '@/i18n/routing';
import { 
    Download, 
    Plus, 
    FileText,
    PieChart,
    Sparkles
} from 'lucide-react';
import FinanceMonthPicker from './FinanceMonthPicker';

export interface CurrencyOption {
    code: string;
    locale: string;
    label: string;
    icon: string;
    symbol: string;
}

export const SUPPORTED_CURRENCIES: CurrencyOption[] = [
    { code: 'IDR', locale: 'id-ID', label: 'Rupiah (Rp)', icon: '🇮🇩', symbol: 'Rp' },
    { code: 'USD', locale: 'en-US', label: 'Dollar ($)', icon: '🇺🇸', symbol: '$' },
    { code: 'GBP', locale: 'en-GB', label: 'Pound (£)', icon: '🇬🇧', symbol: '£' },
    { code: 'EUR', locale: 'de-DE', label: 'Euro (€)', icon: '🇪🇺', symbol: '€' },
    { code: 'JPY', locale: 'ja-JP', label: 'Yen (¥)', icon: '🇯🇵', symbol: '¥' },
];

interface FinanceHeaderProps {
    selectedMonthKey: string;
    onMonthChange: (val: number | string) => void;
    onOpenTrxModal: () => void;
    onOpenBudgetModal?: () => void;
    onOpenBatchModal?: () => void;
    activeCurrency: string;
    onCurrencyChange: (code: string) => void;
    transactions?: any[];
}

export default function FinanceHeader({
    selectedMonthKey,
    onMonthChange,
    onOpenTrxModal,
    activeCurrency,
    onCurrencyChange,
    transactions = []
}: FinanceHeaderProps) {
    const t = useTranslations();
    const locale = useLocale();
    
    const [isExportOpen, setIsExportOpen] = useState(false);
    const [isCurrencyOpen, setIsCurrencyOpen] = useState(false);

    const activeCurrencyObj = SUPPORTED_CURRENCIES.find(c => c.code === activeCurrency) || SUPPORTED_CURRENCIES[0];

    const exportToCSV = () => {
        if (!transactions.length) return alert('No transactions to export.');
        
        const headers = ['Date', 'Title', 'Type', 'Category', 'Amount', 'Currency'];
        const csvRows = [headers.join(',')];
        
        transactions.forEach(t => {
            const date = new Date(t.date).toLocaleDateString('en-CA');
            const title = `"${(t.title || '').replace(/"/g, '""')}"`;
            const type = t.type;
            const category = t.category;
            const amount = t.amount;
            csvRows.push([date, title, type, category, amount, activeCurrency].join(','));
        });
        
        const csvContent = "data:text/csv;charset=utf-8," + csvRows.join('\n');
        const encodedUri = encodeURI(csvContent);
        const link = document.createElement("a");
        link.setAttribute("href", encodedUri);
        link.setAttribute("download", `Tranvas_Finance_${selectedMonthKey}.csv`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        setIsExportOpen(false);
    };

    const exportTaxReport = () => {
        if (!transactions.length) return alert('No transactions to export.');
        
        // Buat jendela cetak baru untuk laporan sederhana
        const printWindow = window.open('', '_blank');
        if (!printWindow) return;
        
        let html = `
            <html>
            <head>
                <title>Laporan Pajak - ${selectedMonthKey}</title>
                <style>
                    body { font-family: 'Courier New', Courier, monospace; padding: 20px; color: #333; }
                    h1 { font-size: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
                    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                    th { background-color: #f5f5f5; }
                    .income { color: #059669; }
                    .expense { color: #dc2626; }
                    .summary { margin-top: 30px; border: 1px solid #333; padding: 15px; background: #fafafa; }
                </style>
            </head>
            <body>
                <h1>Laporan Keuangan & Pajak (Fiscal Report) - ${selectedMonthKey}</h1>
                <p>Generated by <b>Tranvas</b> | Currency: ${activeCurrency}</p>
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Type</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
        `;
        
        let totalIncome = 0;
        let totalExpense = 0;
        
        const sorted = [...transactions].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
        
        sorted.forEach(t => {
            const date = new Date(t.date).toLocaleDateString('en-CA');
            const amt = Number(t.amount);
            if (t.type === 'income') totalIncome += amt;
            else totalExpense += amt;
            
            html += `
                <tr>
                    <td>${date}</td>
                    <td>${t.title}</td>
                    <td>${t.category}</td>
                    <td class="${t.type}">${t.type.toUpperCase()}</td>
                    <td>${amt.toLocaleString()}</td>
                </tr>
            `;
        });
        
        html += `
                    </tbody>
                </table>
                <div class="summary">
                    <h3>Ringkasan Bulan Ini</h3>
                    <p>Total Pemasukan (Bruto): <b>${totalIncome.toLocaleString()}</b></p>
                    <p>Total Pengeluaran: <b>${totalExpense.toLocaleString()}</b></p>
                    <p>Surplus / Defisit: <b>${(totalIncome - totalExpense).toLocaleString()}</b></p>
                </div>
                <script>
                    window.onload = function() { window.print(); }
                </script>
            </body>
            </html>
        `;
        
        printWindow.document.write(html);
        printWindow.document.close();
        setIsExportOpen(false);
    };

    return (
        <div className="relative z-[60] transition-all bg-white dark:bg-slate-900 border-b shadow-sm dark:shadow-none border-slate-100 dark:border-slate-800 transition-colors duration-500">
            <div className="flex flex-col items-stretch justify-between w-full min-w-0 gap-3 md:flex-row md:items-center px-3 sm:px-6 lg:px-8 py-4">
                
                <div className="flex items-center gap-2 w-full min-w-0 md:w-auto md:max-w-[min(100%,28rem)]">
                    <Link 
                        href="/finance/dashboard" 
                        title="Finance Dashboard (Overview Tahunan)" 
                        className="flex items-center justify-center w-9 h-9 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-600 dark:text-slate-400 transition-colors mr-3 shadow-sm"
                    >
                        <PieChart size={18} strokeWidth={2.5} />
                    </Link>
                    <p className="shrink-0 text-[13px] font-black capitalize tracking-wide text-slate-700 dark:text-slate-300 mr-2 pr-4">
                        {t('finance_plan') || 'Finance Plan'}
                    </p>
                </div>

                <div className="flex min-w-0 flex-wrap items-center justify-stretch w-full gap-2 md:w-auto md:flex-nowrap md:justify-end mt-1 md:mt-0">
                    
                    {/* Custom Month Picker — 1:1 from FinanceHeader.vue line 128 */}
                    <FinanceMonthPicker 
                        selectedMonthKey={selectedMonthKey} 
                        onMonthChange={onMonthChange} 
                    />

                    {/* Currency Selector Dropdown — 1:1 from FinanceHeader.vue line 171-197 */}
                    <div className="relative shrink-0 transition-colors duration-500">
                        <button 
                            onClick={() => { setIsCurrencyOpen(!isCurrencyOpen); setIsExportOpen(false); }}
                            className="flex items-center justify-center h-11 px-2.5 transition border bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 rounded-xl gap-1 hover:bg-white dark:hover:bg-slate-700 shadow-sm dark:shadow-none group transition-colors duration-300"
                        >
                            <span className="text-base">{activeCurrencyObj.icon}</span>
                            <span className="text-[9px] font-black text-slate-600 dark:text-slate-300 capitalize">{activeCurrencyObj.code}</span>
                        </button>

                        {isCurrencyOpen && (
                            <div className="absolute right-0 top-full mt-2 w-44 bg-white dark:bg-slate-800 rounded-2xl shadow-xl dark:shadow-none border border-slate-100 dark:border-slate-700 p-1.5 z-[100] origin-top-right transition-colors duration-500">
                                <div className="fixed inset-0 z-[-1]" onClick={() => setIsCurrencyOpen(false)}></div>
                                <div className="relative z-10 space-y-0.5">
                                    {SUPPORTED_CURRENCIES.map(c => (
                                        <button 
                                            key={c.code}
                                            onClick={() => {
                                                onCurrencyChange(c.code);
                                                setIsCurrencyOpen(false);
                                            }} 
                                            className={`w-full flex items-center gap-3 px-3 py-2 rounded-xl transition-colors duration-300 ${activeCurrency === c.code ? 'bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 font-bold' : 'hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-600 dark:text-slate-300'}`}
                                        >
                                            <span className="text-lg">{c.icon}</span>
                                            <span className="text-[11px] font-bold">{c.label}</span>
                                        </button>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Export Actions — 1:1 from FinanceHeader.vue line 200 */}
                    <div className="relative shrink-0 transition-colors duration-500">
                        <button 
                            onClick={() => { setIsExportOpen(!isExportOpen); setIsCurrencyOpen(false); }}
                            className={`flex items-center justify-center h-11 px-3 transition border rounded-xl gap-2 shadow-sm dark:shadow-none group transition-colors duration-300 ${isExportOpen ? 'bg-indigo-50 dark:bg-indigo-500/10 border-indigo-200 dark:border-indigo-500/20' : 'bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:bg-white dark:hover:bg-slate-700'}`}
                        >
                            <Download size={14} strokeWidth={3} className="text-slate-400 group-hover:text-indigo-500" />
                            <span className="text-[10px] font-bold text-slate-600 dark:text-slate-300 tracking-tight hidden lg:inline">{t('export') || 'Export'}</span>
                        </button>

                        {isExportOpen && (
                            <div className="absolute right-0 top-full mt-2 w-48 bg-white dark:bg-slate-800 rounded-2xl shadow-xl dark:shadow-none border border-slate-100 dark:border-slate-700 p-1.5 z-[100] origin-top-right transition-colors duration-500">
                                <div className="fixed inset-0 z-[-1]" onClick={() => setIsExportOpen(false)}></div>
                                <div className="relative z-10 space-y-0.5">
                                    <button onClick={exportToCSV} className="w-full flex items-center gap-3 px-3 py-2.5 hover:bg-slate-50 dark:hover:bg-slate-700 rounded-xl transition-all group/item">
                                        <div className="w-8 h-8 rounded-lg bg-emerald-50 dark:bg-emerald-500/10 flex items-center justify-center text-emerald-500 group-hover/item:scale-110 transition-transform">
                                            <FileText size={14} strokeWidth={2.5} />
                                        </div>
                                        <div className="text-left">
                                            <p className="text-[11px] font-bold text-slate-700 dark:text-slate-200 flex items-center gap-2">Export Excel</p>
                                            <p className="text-[9px] text-slate-400 font-medium">Buka di Excel / Sheets</p>
                                        </div>
                                    </button>
                                    <button onClick={exportTaxReport} className="w-full flex items-center gap-3 px-3 py-2.5 hover:bg-slate-50 dark:hover:bg-slate-700 rounded-xl transition-all group/item">
                                        <div className="w-8 h-8 rounded-lg bg-indigo-50 dark:bg-indigo-500/10 flex items-center justify-center text-indigo-500 group-hover/item:scale-110 transition-transform">
                                            <FileText size={14} strokeWidth={2.5} />
                                        </div>
                                        <div className="text-left">
                                            <p className="text-[11px] font-bold text-slate-700 dark:text-slate-200 text-left">Laporan Pajak</p>
                                            <p className="text-[9px] text-slate-400 font-medium font-mono">Format Fiscal PDF</p>
                                        </div>
                                    </button>
                                    <div className="h-px bg-slate-100 dark:bg-slate-700 mx-3 my-1"></div>
                                    <button className="w-full flex items-center gap-3 px-3 py-2.5 hover:bg-slate-50 dark:hover:bg-slate-700 rounded-xl transition-all group/item">
                                        <div className="w-8 h-8 rounded-lg bg-indigo-50 dark:bg-indigo-500/10 flex items-center justify-center text-indigo-500 group-hover/item:scale-110 transition-transform">
                                            <Sparkles size={14} strokeWidth={2.5} />
                                        </div>
                                        <div className="text-left">
                                            <p className="text-[11px] font-bold text-slate-700 dark:text-slate-200">AI Financial Audit</p>
                                            <p className="text-[9px] text-slate-400 font-medium">Auto-review dari asisten AI</p>
                                        </div>
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>

                    <button 
                        onClick={onOpenTrxModal}
                        className="flex items-center justify-center flex-1 h-11 px-3 md:px-6 transition shadow-lg dark:shadow-none bg-indigo-600 rounded-xl hover:bg-indigo-700 shadow-indigo-100 dark:shadow-indigo-900/40 gap-2 active:scale-95 whitespace-nowrap min-w-0 transition-colors duration-500"
                    >
                        <Plus size={16} strokeWidth={3} className="text-white" />
                        <span className="text-[11px] font-bold text-white tracking-tight truncate">{t('btn_transaction') || 'Transaksi'}</span>
                    </button>
                </div>
                
            </div>
        </div>
    );
}
